AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  PipelineAccountId:
    Type: "String"
Resources:
  CloudFormationActionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CloudFormationCrossAccountDeployment"
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              AWS:
                - !Join ["", ["arn:aws:iam::", {"Ref": "PipelineAccountId"}, ":root"]]
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "cloudformation-deployment"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "cloudformation"
                Effect: "Allow"
                Action:
                   - "cloudformation:*"
                Resource: "*"
              - Sid: "iam"
                Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: "*"
              - Sid: "s3"
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "kms:DescribeKey"
                  - "kms:GenerateDataKey*"
                  - "kms:Encrypt"
                  - "kms:ReEncrypt*"
                  - "kms:Decrypt"
                Resource:
                  - !Join ["", ["arn:aws:kms:", {"Ref": "AWS::Region"}, ":", {"Ref": "PipelineAccountId"}, ":key/*"]]

  CloudFormationServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CloudFormationServiceRole"
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
                Service:
                    - "cloudformation.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "admin"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
